# Generated by Django 5.2.13 on 2026-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='compromise_detected',
            field=models.BooleanField(default=False),
        ),
    ]
