# Generated by Django 5.2.13 on 2026-05-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('api_access', 'API Access')], max_length=50)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('user_agent', models.TextField()),
                ('username', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('ATTACK', 'Attack'), ('SUSPICIOUS', 'Suspicious'), ('NORMAL', 'Normal')], max_length=20)),
                ('attack_type', models.CharField(choices=[('brute_force', 'Brute Force'), ('anomaly', 'Anomaly'), ('blacklisted', 'Blacklisted'), ('none', 'None')], max_length=50)),
                ('confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logs.log')),
            ],
        ),
    ]
