# Generated by Django 5.2.13 on 2026-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(choices=[('brute_force', 'Brute Force'), ('suspicious_login', 'Suspicious Login'), ('blacklisted_ip', 'Blacklisted IP'), ('none', 'None')], max_length=50),
        ),
    ]
