# Generated by Django 5.2.13 on 2026-05-31

from django.db import migrations

def update_ml_alerts(apps, schema_editor):
    Alert = apps.get_model('logs', 'Alert')
    
    # 1. Replace normal ML reasons with rule-based text
    Alert.objects.filter(
        reason__icontains="ML model classified event as normal behavior"
    ).update(
        reason="Log traffic conforms to normal signature rules"
    )

    Alert.objects.filter(
        reason__icontains="ML model unavailable"
    ).update(
        reason="Log traffic conforms to normal signature rules"
    )

    # 2. Replace anomalous ML reasons with rule-based suspicious reasons
    # and map the attack type from "anomaly" to "suspicious_login"
    Alert.objects.filter(
        reason__icontains="ML model detected anomalous behavior pattern"
    ).update(
        attack_type="suspicious_login",
        reason="Suspicious login activity: anomalous request signature detected"
    )

    # 3. Handle mapping of older database fields choice keys to new choice keys
    # Map 'anomaly' to 'suspicious_login'
    Alert.objects.filter(attack_type="anomaly").update(attack_type="suspicious_login")
    
    # Map 'blacklisted' to 'blacklisted_ip'
    Alert.objects.filter(attack_type="blacklisted").update(attack_type="blacklisted_ip")


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_alert_attack_type'),
    ]

    operations = [
        migrations.RunPython(update_ml_alerts, reverse_code=migrations.RunPython.noop),
    ]
