# Generated by Django 5.2.13 on 2026-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_cleanup_ml_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
