# Generated by Django 5.2.13 on 2026-06-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='attack_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alert',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
