# Generated by Django 5.2.13 on 2026-06-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20260602_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='attack_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='attack_type',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='campaign_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='campaign_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='log',
            name='reason',
            field=models.TextField(blank=True, default='Pending classification'),
        ),
        migrations.AddField(
            model_name='log',
            name='request_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='verdict',
            field=models.CharField(blank=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(choices=[('brute_force', 'Brute Force'), ('suspicious_login', 'Suspicious Login'), ('blacklisted_ip', 'Blacklisted IP'), ('credential_stuffing', 'Credential Stuffing'), ('sql_injection', 'SQL Injection'), ('none', 'None')], max_length=50),
        ),
    ]
