# Generated by Django 5.2.13 on 2026-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_backpopulate_log_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='compromise_detected',
            field=models.BooleanField(default=False),
        ),
    ]
