# Generated by Django 5.2.13 on 2026-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alert_compromise_detected'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
